[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
futures = "0.3.31"
reqwest = "0.12.9"
tokio = {version="1.42.0", features=["sync", "rt", "rt-multi-thread", "macros"]}
